VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "cIAFIPParametro"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Let Title2(ByVal rhs As String)
End Property

Public Property Get ID() As Long
End Property

Public Property Let ID(ByVal rhs As Long)
End Property

Public Property Get Nombre() As String
End Property

Public Property Let Nombre(ByVal rhs As String)
End Property

Public Property Get Descrip() As String
End Property

Public Property Let Descrip(ByVal rhs As String)
End Property

Public Property Get Tipo() As csTypeABMProperty
End Property

Public Property Let Tipo(ByVal rhs As csTypeABMProperty)
End Property

Public Property Get SubTipo() As csSubTypeABMProperty
End Property

Public Property Let SubTipo(ByVal rhs As csSubTypeABMProperty)
End Property

Public Property Get TablaHelp() As Long
End Property

Public Property Let TablaHelp(ByVal rhs As Long)
End Property

Public Property Get Valor() As String
End Property

Public Property Let Valor(ByVal rhs As String)
End Property

Public Property Get Avanzado() As Boolean
End Property

Public Property Let Avanzado(ByVal rhs As Boolean)
End Property

Public Property Get Esquema() As String
End Property

Public Property Let Esquema(ByVal rhs As String)
End Property

