'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
'
Namespace ar.gov.afip.wswhomo
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceSoap", [Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private FERecuperaQTYRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FEDummyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FERecuperaLastCMPRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FEUltNroRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FEAutRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FEConsultaCAERequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CSFacturaElectronica.My.MySettings.Default.CSFacturaElectronica_ar_gov_afip_wswhomo_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event FERecuperaQTYRequestCompleted As FERecuperaQTYRequestCompletedEventHandler
        
        '''<remarks/>
        Public Event FEDummyCompleted As FEDummyCompletedEventHandler
        
        '''<remarks/>
        Public Event FERecuperaLastCMPRequestCompleted As FERecuperaLastCMPRequestCompletedEventHandler
        
        '''<remarks/>
        Public Event FEUltNroRequestCompleted As FEUltNroRequestCompletedEventHandler
        
        '''<remarks/>
        Public Event FEAutRequestCompleted As FEAutRequestCompletedEventHandler
        
        '''<remarks/>
        Public Event FEConsultaCAERequestCompleted As FEConsultaCAERequestCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.facturaelectronica/FERecuperaQTYRequest", RequestNamespace:="http://ar.gov.afip.dif.facturaelectronica/", ResponseNamespace:="http://ar.gov.afip.dif.facturaelectronica/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FERecuperaQTYRequest(ByVal argAuth As FEAuthRequest) As FERecuperaQTYResponse
            Dim results() As Object = Me.Invoke("FERecuperaQTYRequest", New Object() {argAuth})
            Return CType(results(0),FERecuperaQTYResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub FERecuperaQTYRequestAsync(ByVal argAuth As FEAuthRequest)
            Me.FERecuperaQTYRequestAsync(argAuth, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FERecuperaQTYRequestAsync(ByVal argAuth As FEAuthRequest, ByVal userState As Object)
            If (Me.FERecuperaQTYRequestOperationCompleted Is Nothing) Then
                Me.FERecuperaQTYRequestOperationCompleted = AddressOf Me.OnFERecuperaQTYRequestOperationCompleted
            End If
            Me.InvokeAsync("FERecuperaQTYRequest", New Object() {argAuth}, Me.FERecuperaQTYRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnFERecuperaQTYRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.FERecuperaQTYRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FERecuperaQTYRequestCompleted(Me, New FERecuperaQTYRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.facturaelectronica/FEDummy", RequestNamespace:="http://ar.gov.afip.dif.facturaelectronica/", ResponseNamespace:="http://ar.gov.afip.dif.facturaelectronica/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FEDummy() As DummyResponse
            Dim results() As Object = Me.Invoke("FEDummy", New Object(-1) {})
            Return CType(results(0),DummyResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub FEDummyAsync()
            Me.FEDummyAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FEDummyAsync(ByVal userState As Object)
            If (Me.FEDummyOperationCompleted Is Nothing) Then
                Me.FEDummyOperationCompleted = AddressOf Me.OnFEDummyOperationCompleted
            End If
            Me.InvokeAsync("FEDummy", New Object(-1) {}, Me.FEDummyOperationCompleted, userState)
        End Sub
        
        Private Sub OnFEDummyOperationCompleted(ByVal arg As Object)
            If (Not (Me.FEDummyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FEDummyCompleted(Me, New FEDummyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.facturaelectronica/FERecuperaLastCMPRequest", RequestNamespace:="http://ar.gov.afip.dif.facturaelectronica/", ResponseNamespace:="http://ar.gov.afip.dif.facturaelectronica/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FERecuperaLastCMPRequest(ByVal argAuth As FEAuthRequest, ByVal argTCMP As FELastCMPtype) As FERecuperaLastCMPResponse
            Dim results() As Object = Me.Invoke("FERecuperaLastCMPRequest", New Object() {argAuth, argTCMP})
            Return CType(results(0),FERecuperaLastCMPResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub FERecuperaLastCMPRequestAsync(ByVal argAuth As FEAuthRequest, ByVal argTCMP As FELastCMPtype)
            Me.FERecuperaLastCMPRequestAsync(argAuth, argTCMP, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FERecuperaLastCMPRequestAsync(ByVal argAuth As FEAuthRequest, ByVal argTCMP As FELastCMPtype, ByVal userState As Object)
            If (Me.FERecuperaLastCMPRequestOperationCompleted Is Nothing) Then
                Me.FERecuperaLastCMPRequestOperationCompleted = AddressOf Me.OnFERecuperaLastCMPRequestOperationCompleted
            End If
            Me.InvokeAsync("FERecuperaLastCMPRequest", New Object() {argAuth, argTCMP}, Me.FERecuperaLastCMPRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnFERecuperaLastCMPRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.FERecuperaLastCMPRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FERecuperaLastCMPRequestCompleted(Me, New FERecuperaLastCMPRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.facturaelectronica/FEUltNroRequest", RequestNamespace:="http://ar.gov.afip.dif.facturaelectronica/", ResponseNamespace:="http://ar.gov.afip.dif.facturaelectronica/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FEUltNroRequest(ByVal argAuth As FEAuthRequest) As FEUltNroResponse
            Dim results() As Object = Me.Invoke("FEUltNroRequest", New Object() {argAuth})
            Return CType(results(0),FEUltNroResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub FEUltNroRequestAsync(ByVal argAuth As FEAuthRequest)
            Me.FEUltNroRequestAsync(argAuth, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FEUltNroRequestAsync(ByVal argAuth As FEAuthRequest, ByVal userState As Object)
            If (Me.FEUltNroRequestOperationCompleted Is Nothing) Then
                Me.FEUltNroRequestOperationCompleted = AddressOf Me.OnFEUltNroRequestOperationCompleted
            End If
            Me.InvokeAsync("FEUltNroRequest", New Object() {argAuth}, Me.FEUltNroRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnFEUltNroRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.FEUltNroRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FEUltNroRequestCompleted(Me, New FEUltNroRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.facturaelectronica/FEAutRequest", RequestNamespace:="http://ar.gov.afip.dif.facturaelectronica/", ResponseNamespace:="http://ar.gov.afip.dif.facturaelectronica/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FEAutRequest(ByVal argAuth As FEAuthRequest, ByVal Fer As FERequest) As FEResponse
            Dim results() As Object = Me.Invoke("FEAutRequest", New Object() {argAuth, Fer})
            Return CType(results(0),FEResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub FEAutRequestAsync(ByVal argAuth As FEAuthRequest, ByVal Fer As FERequest)
            Me.FEAutRequestAsync(argAuth, Fer, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FEAutRequestAsync(ByVal argAuth As FEAuthRequest, ByVal Fer As FERequest, ByVal userState As Object)
            If (Me.FEAutRequestOperationCompleted Is Nothing) Then
                Me.FEAutRequestOperationCompleted = AddressOf Me.OnFEAutRequestOperationCompleted
            End If
            Me.InvokeAsync("FEAutRequest", New Object() {argAuth, Fer}, Me.FEAutRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnFEAutRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.FEAutRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FEAutRequestCompleted(Me, New FEAutRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.facturaelectronica/FEConsultaCAERequest", RequestNamespace:="http://ar.gov.afip.dif.facturaelectronica/", ResponseNamespace:="http://ar.gov.afip.dif.facturaelectronica/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FEConsultaCAERequest(ByVal argAuth As FEAuthRequest, ByVal argCAERequest As FEConsultaCAEReq) As FEConsultaCAEResponse
            Dim results() As Object = Me.Invoke("FEConsultaCAERequest", New Object() {argAuth, argCAERequest})
            Return CType(results(0),FEConsultaCAEResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub FEConsultaCAERequestAsync(ByVal argAuth As FEAuthRequest, ByVal argCAERequest As FEConsultaCAEReq)
            Me.FEConsultaCAERequestAsync(argAuth, argCAERequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FEConsultaCAERequestAsync(ByVal argAuth As FEAuthRequest, ByVal argCAERequest As FEConsultaCAEReq, ByVal userState As Object)
            If (Me.FEConsultaCAERequestOperationCompleted Is Nothing) Then
                Me.FEConsultaCAERequestOperationCompleted = AddressOf Me.OnFEConsultaCAERequestOperationCompleted
            End If
            Me.InvokeAsync("FEConsultaCAERequest", New Object() {argAuth, argCAERequest}, Me.FEConsultaCAERequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnFEConsultaCAERequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.FEConsultaCAERequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FEConsultaCAERequestCompleted(Me, New FEConsultaCAERequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class FEAuthRequest
        
        Private tokenField As String
        
        Private signField As String
        
        Private cuitField As Long
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sign() As String
            Get
                Return Me.signField
            End Get
            Set
                Me.signField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cuit() As Long
            Get
                Return Me.cuitField
            End Get
            Set
                Me.cuitField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class FEConsultaCAEResponse
        
        Private resultadoField As Integer
        
        Private rErrorField As vError
        
        '''<remarks/>
        Public Property Resultado() As Integer
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RError() As vError
            Get
                Return Me.rErrorField
            End Get
            Set
                Me.rErrorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class vError
        
        Private percodeField As Integer
        
        Private perrmsgField As String
        
        '''<remarks/>
        Public Property percode() As Integer
            Get
                Return Me.percodeField
            End Get
            Set
                Me.percodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property perrmsg() As String
            Get
                Return Me.perrmsgField
            End Get
            Set
                Me.perrmsgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class FEConsultaCAEReq
        
        Private cuit_emisorField As Long
        
        Private tipo_cbteField As Integer
        
        Private punto_vtaField As Integer
        
        Private cbt_nroField As Long
        
        Private imp_totalField As Double
        
        Private caeField As String
        
        Private fecha_cbteField As String
        
        '''<remarks/>
        Public Property cuit_emisor() As Long
            Get
                Return Me.cuit_emisorField
            End Get
            Set
                Me.cuit_emisorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tipo_cbte() As Integer
            Get
                Return Me.tipo_cbteField
            End Get
            Set
                Me.tipo_cbteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property punto_vta() As Integer
            Get
                Return Me.punto_vtaField
            End Get
            Set
                Me.punto_vtaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cbt_nro() As Long
            Get
                Return Me.cbt_nroField
            End Get
            Set
                Me.cbt_nroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property imp_total() As Double
            Get
                Return Me.imp_totalField
            End Get
            Set
                Me.imp_totalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cae() As String
            Get
                Return Me.caeField
            End Get
            Set
                Me.caeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fecha_cbte() As String
            Get
                Return Me.fecha_cbteField
            End Get
            Set
                Me.fecha_cbteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class FEDetalleResponse
        
        Private tipo_docField As Integer
        
        Private nro_docField As Long
        
        Private tipo_cbteField As Integer
        
        Private punto_vtaField As Integer
        
        Private cbt_desdeField As Long
        
        Private cbt_hastaField As Long
        
        Private imp_totalField As Double
        
        Private imp_tot_concField As Double
        
        Private imp_netoField As Double
        
        Private impto_liqField As Double
        
        Private impto_liq_rniField As Double
        
        Private imp_op_exField As Double
        
        Private resultadoField As String
        
        Private caeField As String
        
        Private fecha_cbteField As String
        
        Private fecha_vtoField As String
        
        Private motivoField As String
        
        Private fecha_serv_desdeField As String
        
        Private fecha_serv_hastaField As String
        
        Private fecha_venc_pagoField As String
        
        '''<remarks/>
        Public Property tipo_doc() As Integer
            Get
                Return Me.tipo_docField
            End Get
            Set
                Me.tipo_docField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nro_doc() As Long
            Get
                Return Me.nro_docField
            End Get
            Set
                Me.nro_docField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tipo_cbte() As Integer
            Get
                Return Me.tipo_cbteField
            End Get
            Set
                Me.tipo_cbteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property punto_vta() As Integer
            Get
                Return Me.punto_vtaField
            End Get
            Set
                Me.punto_vtaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cbt_desde() As Long
            Get
                Return Me.cbt_desdeField
            End Get
            Set
                Me.cbt_desdeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cbt_hasta() As Long
            Get
                Return Me.cbt_hastaField
            End Get
            Set
                Me.cbt_hastaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property imp_total() As Double
            Get
                Return Me.imp_totalField
            End Get
            Set
                Me.imp_totalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property imp_tot_conc() As Double
            Get
                Return Me.imp_tot_concField
            End Get
            Set
                Me.imp_tot_concField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property imp_neto() As Double
            Get
                Return Me.imp_netoField
            End Get
            Set
                Me.imp_netoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property impto_liq() As Double
            Get
                Return Me.impto_liqField
            End Get
            Set
                Me.impto_liqField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property impto_liq_rni() As Double
            Get
                Return Me.impto_liq_rniField
            End Get
            Set
                Me.impto_liq_rniField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property imp_op_ex() As Double
            Get
                Return Me.imp_op_exField
            End Get
            Set
                Me.imp_op_exField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property resultado() As String
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cae() As String
            Get
                Return Me.caeField
            End Get
            Set
                Me.caeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fecha_cbte() As String
            Get
                Return Me.fecha_cbteField
            End Get
            Set
                Me.fecha_cbteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fecha_vto() As String
            Get
                Return Me.fecha_vtoField
            End Get
            Set
                Me.fecha_vtoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property motivo() As String
            Get
                Return Me.motivoField
            End Get
            Set
                Me.motivoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fecha_serv_desde() As String
            Get
                Return Me.fecha_serv_desdeField
            End Get
            Set
                Me.fecha_serv_desdeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fecha_serv_hasta() As String
            Get
                Return Me.fecha_serv_hastaField
            End Get
            Set
                Me.fecha_serv_hastaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fecha_venc_pago() As String
            Get
                Return Me.fecha_venc_pagoField
            End Get
            Set
                Me.fecha_venc_pagoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class FECabeceraResponse
        
        Private idField As Long
        
        Private cuitField As Long
        
        Private fecha_caeField As String
        
        Private cantidadregField As Integer
        
        Private resultadoField As String
        
        Private motivoField As String
        
        Private reprocesoField As String
        
        Private presta_servField As Integer
        
        '''<remarks/>
        Public Property id() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cuit() As Long
            Get
                Return Me.cuitField
            End Get
            Set
                Me.cuitField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fecha_cae() As String
            Get
                Return Me.fecha_caeField
            End Get
            Set
                Me.fecha_caeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cantidadreg() As Integer
            Get
                Return Me.cantidadregField
            End Get
            Set
                Me.cantidadregField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property resultado() As String
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property motivo() As String
            Get
                Return Me.motivoField
            End Get
            Set
                Me.motivoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property reproceso() As String
            Get
                Return Me.reprocesoField
            End Get
            Set
                Me.reprocesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property presta_serv() As Integer
            Get
                Return Me.presta_servField
            End Get
            Set
                Me.presta_servField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class FEResponse
        
        Private fecRespField As FECabeceraResponse
        
        Private fedRespField() As FEDetalleResponse
        
        Private rErrorField As vError
        
        '''<remarks/>
        Public Property FecResp() As FECabeceraResponse
            Get
                Return Me.fecRespField
            End Get
            Set
                Me.fecRespField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FedResp() As FEDetalleResponse()
            Get
                Return Me.fedRespField
            End Get
            Set
                Me.fedRespField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RError() As vError
            Get
                Return Me.rErrorField
            End Get
            Set
                Me.rErrorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class FEDetalleRequest
        
        Private tipo_docField As Integer
        
        Private nro_docField As Long
        
        Private tipo_cbteField As Integer
        
        Private punto_vtaField As Integer
        
        Private cbt_desdeField As Long
        
        Private cbt_hastaField As Long
        
        Private imp_totalField As Double
        
        Private imp_tot_concField As Double
        
        Private imp_netoField As Double
        
        Private impto_liqField As Double
        
        Private impto_liq_rniField As Double
        
        Private imp_op_exField As Double
        
        Private fecha_cbteField As String
        
        Private fecha_serv_desdeField As String
        
        Private fecha_serv_hastaField As String
        
        Private fecha_venc_pagoField As String
        
        '''<remarks/>
        Public Property tipo_doc() As Integer
            Get
                Return Me.tipo_docField
            End Get
            Set
                Me.tipo_docField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nro_doc() As Long
            Get
                Return Me.nro_docField
            End Get
            Set
                Me.nro_docField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tipo_cbte() As Integer
            Get
                Return Me.tipo_cbteField
            End Get
            Set
                Me.tipo_cbteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property punto_vta() As Integer
            Get
                Return Me.punto_vtaField
            End Get
            Set
                Me.punto_vtaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cbt_desde() As Long
            Get
                Return Me.cbt_desdeField
            End Get
            Set
                Me.cbt_desdeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cbt_hasta() As Long
            Get
                Return Me.cbt_hastaField
            End Get
            Set
                Me.cbt_hastaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property imp_total() As Double
            Get
                Return Me.imp_totalField
            End Get
            Set
                Me.imp_totalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property imp_tot_conc() As Double
            Get
                Return Me.imp_tot_concField
            End Get
            Set
                Me.imp_tot_concField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property imp_neto() As Double
            Get
                Return Me.imp_netoField
            End Get
            Set
                Me.imp_netoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property impto_liq() As Double
            Get
                Return Me.impto_liqField
            End Get
            Set
                Me.impto_liqField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property impto_liq_rni() As Double
            Get
                Return Me.impto_liq_rniField
            End Get
            Set
                Me.impto_liq_rniField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property imp_op_ex() As Double
            Get
                Return Me.imp_op_exField
            End Get
            Set
                Me.imp_op_exField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fecha_cbte() As String
            Get
                Return Me.fecha_cbteField
            End Get
            Set
                Me.fecha_cbteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fecha_serv_desde() As String
            Get
                Return Me.fecha_serv_desdeField
            End Get
            Set
                Me.fecha_serv_desdeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fecha_serv_hasta() As String
            Get
                Return Me.fecha_serv_hastaField
            End Get
            Set
                Me.fecha_serv_hastaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fecha_venc_pago() As String
            Get
                Return Me.fecha_venc_pagoField
            End Get
            Set
                Me.fecha_venc_pagoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class FECabeceraRequest
        
        Private idField As Long
        
        Private cantidadregField As Integer
        
        Private presta_servField As Integer
        
        '''<remarks/>
        Public Property id() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cantidadreg() As Integer
            Get
                Return Me.cantidadregField
            End Get
            Set
                Me.cantidadregField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property presta_serv() As Integer
            Get
                Return Me.presta_servField
            End Get
            Set
                Me.presta_servField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class FERequest
        
        Private fecrField As FECabeceraRequest
        
        Private fedrField() As FEDetalleRequest
        
        '''<remarks/>
        Public Property Fecr() As FECabeceraRequest
            Get
                Return Me.fecrField
            End Get
            Set
                Me.fecrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fedr() As FEDetalleRequest()
            Get
                Return Me.fedrField
            End Get
            Set
                Me.fedrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class UltNroResponse
        
        Private valueField As Long
        
        '''<remarks/>
        Public Property value() As Long
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class FEUltNroResponse
        
        Private nroField As UltNroResponse
        
        Private rErrorField As vError
        
        '''<remarks/>
        Public Property nro() As UltNroResponse
            Get
                Return Me.nroField
            End Get
            Set
                Me.nroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RError() As vError
            Get
                Return Me.rErrorField
            End Get
            Set
                Me.rErrorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class FERecuperaLastCMPResponse
        
        Private cbte_nroField As Integer
        
        Private rErrorField As vError
        
        '''<remarks/>
        Public Property cbte_nro() As Integer
            Get
                Return Me.cbte_nroField
            End Get
            Set
                Me.cbte_nroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RError() As vError
            Get
                Return Me.rErrorField
            End Get
            Set
                Me.rErrorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class FELastCMPtype
        
        Private ptoVtaField As Integer
        
        Private tipoCbteField As Integer
        
        '''<remarks/>
        Public Property PtoVta() As Integer
            Get
                Return Me.ptoVtaField
            End Get
            Set
                Me.ptoVtaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoCbte() As Integer
            Get
                Return Me.tipoCbteField
            End Get
            Set
                Me.tipoCbteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class DummyResponse
        
        Private appserverField As String
        
        Private dbserverField As String
        
        Private authserverField As String
        
        '''<remarks/>
        Public Property appserver() As String
            Get
                Return Me.appserverField
            End Get
            Set
                Me.appserverField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property dbserver() As String
            Get
                Return Me.dbserverField
            End Get
            Set
                Me.dbserverField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property authserver() As String
            Get
                Return Me.authserverField
            End Get
            Set
                Me.authserverField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class FERecuperaQTY
        
        Private valueField As Integer
        
        '''<remarks/>
        Public Property value() As Integer
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ar.gov.afip.dif.facturaelectronica/")>  _
    Partial Public Class FERecuperaQTYResponse
        
        Private qtyField As FERecuperaQTY
        
        Private rErrorField As vError
        
        '''<remarks/>
        Public Property qty() As FERecuperaQTY
            Get
                Return Me.qtyField
            End Get
            Set
                Me.qtyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RError() As vError
            Get
                Return Me.rErrorField
            End Get
            Set
                Me.rErrorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub FERecuperaQTYRequestCompletedEventHandler(ByVal sender As Object, ByVal e As FERecuperaQTYRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FERecuperaQTYRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As FERecuperaQTYResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),FERecuperaQTYResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub FEDummyCompletedEventHandler(ByVal sender As Object, ByVal e As FEDummyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FEDummyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DummyResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DummyResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub FERecuperaLastCMPRequestCompletedEventHandler(ByVal sender As Object, ByVal e As FERecuperaLastCMPRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FERecuperaLastCMPRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As FERecuperaLastCMPResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),FERecuperaLastCMPResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub FEUltNroRequestCompletedEventHandler(ByVal sender As Object, ByVal e As FEUltNroRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FEUltNroRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As FEUltNroResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),FEUltNroResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub FEAutRequestCompletedEventHandler(ByVal sender As Object, ByVal e As FEAutRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FEAutRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As FEResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),FEResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub FEConsultaCAERequestCompletedEventHandler(ByVal sender As Object, ByVal e As FEConsultaCAERequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FEConsultaCAERequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As FEConsultaCAEResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),FEConsultaCAEResponse)
            End Get
        End Property
    End Class
End Namespace
