VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "cIABMDocEvent"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
'--------------------------------------------------------------------------------
' cIABMDocsub
' 16-05-04

'--------------------------------------------------------------------------------
' notas:

'--------------------------------------------------------------------------------
' api win32
    ' constantes
    ' estructuras
    ' funciones
'--------------------------------------------------------------------------------

' constantes
' estructuras
' variables privadas
' subos
' propiedades publicas
' propiedades privadas
' funciones publicas
Public Sub CBChange(ByVal Index As Integer)
End Sub
Public Sub CBhockChange(ByVal Index As Integer)
End Sub
Public Sub CHKClick(ByVal Index As Integer)
End Sub
Public Sub cmdCancelClick()
End Sub
Public Sub cmdSaveClick()
End Sub
Public Sub cmdCloseClick()
End Sub
Public Sub HLChange(ByVal Index As Integer)
End Sub
Public Sub MEChange(ByVal Index As Integer)
End Sub
Public Sub MEDateChange(ByVal Index As Integer)
End Sub
Public Sub OPClick(ByVal Index As Integer)
End Sub
Public Sub TXChange(ByVal Index As Integer)
End Sub
Public Sub TXPasswordChange(ByVal Index As Integer)
End Sub
Public Sub FormUnload(ByRef Cancel As Integer)
End Sub
Public Sub FormLoad()
End Sub
Public Sub FormQueryUnload(ByRef Cancel As Integer, ByVal UnloadMode As Integer)
End Sub
Public Sub cbTabClick(ByVal Index As Integer, ByVal Tag As String)
End Sub
Public Sub CMDClick(ByVal Index As Integer)
End Sub
Public Sub GRColumnButtonClick(ByVal Index As Integer, ByVal lRow As Long, ByVal lCol As Long, ByVal iKeyAscii As Integer, bCancel As Boolean)
End Sub
Public Sub GRColumnAfterEdit(ByVal Index As Integer, ByVal lRow As Long, ByVal lCol As Long, ByVal NewValue As Variant, ByVal NewValueID As Long, ByRef bCancel As Boolean)
End Sub
Public Sub GRColumnAfterUpdate(ByVal Index As Integer, ByVal lRow As Long, ByVal lCol As Long, ByVal NewValue As Variant, ByVal NewValueID As Long)
End Sub
Public Sub GRColumnBeforeEdit(ByVal Index As Integer, ByVal lRow As Long, ByVal lCol As Long, ByVal iKeyAscii As Integer, ByRef bCancel As Boolean)
End Sub
Public Sub GRClick(ByVal Index As Integer)
End Sub
Public Sub GRDblClick(ByVal Index As Integer, ByVal RowIndex As Long, ByVal ColIndex As Long)
End Sub
Public Sub GRValidateRow(ByVal Index As Integer, ByVal RowIndex As Long, ByRef bCancel As Boolean)
End Sub
Public Sub GRNewRow(ByVal Index As Integer, ByVal RowIndex As Long)
End Sub
Public Sub GRDeleteRow(Index As Integer, ByVal lRow As Long, bCancel As Boolean)
End Sub
Public Sub ToolBarClick(ByVal Button As Object)
End Sub
Public Sub cmdNextClick()
End Sub
Public Sub cmdBackClick()
End Sub
Public Sub GRSelectionChange(Index As Integer, ByVal lRow As Long, ByVal lCol As Long)
End Sub
Public Sub ToolBarButtonClick(ByVal Button As Object)
End Sub
