select 'delete ' + name from sysobjects where name like '%tmp' and xtype = 'u'


delete PedidoFacturaVentaTMP
delete PermisoEmbarqueItemBorradoTMP
delete StockItemTMP
delete PedidoRemitoVentaTMP
delete FacturaCompraItemSerieTMP
delete DepositoBancoItemTMP
delete FacturaVentaItemSerieTMP
delete FacturaCompraItemTMP
delete PedidoCompraTMP
delete ImportacionTempItemTMP
delete ParteProdKitItemBorradoTMP
delete FacturaCompraTMP
delete ParteProdKitItemSerieTMP
delete ParteProdKitItemTMP
delete ParteProdKitTMP
delete ManifiestoCargaTMP
delete PresupuestoVentaItemBorradoTMP
delete PresupuestoVentaItemTMP
delete PresupuestoVentaTMP
delete RecuentoStockItemSerieTMP
delete FacturaCompraOtroTMP
delete OrdenPagoTMP
delete RemitoVentaItemSerieTMP
delete AsientoTMP
delete PackingListTMP
delete CobranzaItemBorradoTMP
delete FacturaCompraOrdenPagoTMP
delete OrdenPagoItemBorradoTMP
delete CobranzaTMP
delete MovimientoFondoItemTMP
delete FacturaCompraItemBorradoTMP
delete FacturaCompraOtroBorradoTMP
delete RecuentoStockTMP
delete FacturaCompraNotaCreditoTMP
delete AsientoItemBorradoTMP
delete PedidoPackingListTMP
delete RemitoVentaTMP
delete RemitoDevolucionCompraTMP
delete RecuentoStockItemTMP
delete FacturaVentaNotaCreditoTMP
delete DepositoCuponItemBorradoTMP
delete DepositoCuponItemTMP
delete DepositoCuponTMP
delete CobranzaItemTMP
delete RemitoFacturaCompraTMP
delete FacturaCompraPercepcionTMP
delete ResolucionCuponItemBorradoTMP
delete ResolucionCuponItemTMP
delete RemitoDevolucionVentaTMP
delete ResolucionCuponTMP
delete PackingListItemBorradoTMP
delete PedidoVentaItemTMP
delete DepositoBancoItemBorradoTMP
delete FacturaCompraPercepcionBorradoTMP
delete StockTMP
delete PedidoCompraItemTMP
delete RemitoCompraItemBorradoTMP
delete ManifiestoCargaItemBorradoTMP
delete PedidoDevolucionCompraTMP
delete PermisoEmbarqueItemTMP
delete PedidoDevolucionVentaTMP
delete ImportacionTempItemBorradoTMP
delete ImportacionTempItemSerieTMP
delete PedidoRemitoCompraTMP
delete PedidoVentaTMP
delete ManifiestoCargaItemTMP
delete OrdenPagoItemTMP
delete MovimientoFondoTMP
delete RemitoCompraItemSerieTMP
delete FacturaVentaTMP
delete ImportacionTempGarantiaTMP
delete ManifiestoPackingListTMP
delete PackingListDevolucionTMP
delete RemitoCompraItemTMP
delete PedidoCompraItemBorradoTMP
delete PackingListItemTMP
delete FacturaVentaItemTMP
delete RemitoVentaItemBorradoTMP
delete ImportacionTempTMP
delete RemitoVentaItemTMP
delete PedidoFacturaCompraTMP
delete RendicionItemTMP
delete RendicionTMP
delete PermisoEmbarqueTMP
delete FacturaVentaItemBorradoTMP
delete PedidoVentaItemBorradoTMP
delete MovimientoFondoRendicionTMP
delete AsientoItemTMP
delete MovimientoFondoItemBorradoTMP
delete DepositoBancoTMP
delete FacturaCompraLegajoBorradoTMP
delete RemitoCompraTMP
delete FacturaCompraLegajoTMP
delete PackingListFacturaVentaTMP
delete RemitoFacturaVentaTMP
delete FacturaVentaCobranzaTMP
