delete pedidoremitoventa
delete pedidofacturaventa
delete pedidoventaitem
delete pedidoventaitemstock
delete pedidoventa
delete remitofacturaventa
delete remitoventaitem
delete remitoventa
delete facturaventaitem
delete facturaventadeuda
delete facturaventapago
delete facturaventa
delete pedidofacturacompra
delete pedidoremitocompra
delete pedidocompraitem
delete pedidocompra
delete remitofacturacompra
delete remitocompraitem
delete remitocompra
delete facturacompraitem
delete facturacompraordenpago
delete facturacompradeuda
delete facturacomprapago
delete facturacomprapercepcion
delete facturacompra
update productonumeroserie set ppk_id = null
delete parteprodkititem
delete parteprodkit
delete recuentostockitem
delete recuentostock
delete stockitem
delete stockitemkit
delete stock