Attribute VB_Name = "mConstantes"
Option Explicit

'Const adEmpty = 0
'Const adTinyInt = 16
'Const adSmallInt = 2
'Const adInteger = 3
'Const adBigInt = 20
'Const adUnsignedTinyInt = 17
'Const adUnsignedSmallInt = 18
'Const adUnsignedInt = 19
'Const adUnsignedBigInt = 21
'Const adSingle = 4
'Const adDouble = 5
'Const adCurrency = 6
'Const adDecimal = 14
'Const adNumeric = 131
'Const adBoolean = 11
'Const adError = 10
'Const adUserDefined = 132
'Const adVariant = 12
'Const adIDispatch = 9
'Const adIUnknown = 13
'Const adGUID = 72
Public Const adDate = 7
Public Const adDBDate = 133
Public Const adDBTime = 134
Public Const adDBTimeStamp = 135
Public Const adBSTR = 8
'Const adChar = 129
'Const adVarChar = 200
'Const adLongVarChar = 201
'Const adWChar = 130
'Const adVarWChar = 202
'Const adLongVarWChar = 203
'Const adBinary = 128
'Const adVarBinary = 204
'Const adLongVarBinary = 205
'Const adChapter = 136
'Const adFileTime = 64
'Const adPropVariant = 138
'Const adVarNumeric = 139
'Const adArray = &H2000
