VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "cDeclaration"
Attribute VB_GlobalNameSpace = True
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

'--------------------------------------------------------------------------------
' cCheckedItem
' 03-10-00

'--------------------------------------------------------------------------------
' notas:

'--------------------------------------------------------------------------------
' api win32
    ' constantes
    ' estructuras
    ' funciones

'--------------------------------------------------------------------------------

' constantes
Public Enum csBorderType
  cNone = 0
  cSingle = 1
End Enum

Public Enum csTextMascara
  csMkMoney = 1
  csMkInteger = 2
  csMkDouble = 3
  csMkPercent = 4
  csMkText = 5
  csMkDate = 6
  csMkTime = 7
  csMkFile = 8
  csMkFolder = 9
End Enum

Public Enum csButtonStyle
  cButtonNone = 0
  cButtonSingle = 1
End Enum

' estructuras
' variables privadas
' propiedades publicas
' propiedades privadas
' funciones publicas
' funciones privadas
' construccion - destruccion






