declare @fecha datetime set @fecha = getdate()
select * from facturaventa where fv_fecha > @fecha or fv_fecha < '20041230'
select * from facturacompra where fc_fecha > @fecha or fc_fecha < '20041230'
select * from remitoventa where rv_fecha > @fecha or rv_fecha < '20041230'
select * from remitocompra where rc_fecha > @fecha or rc_fecha < '20041230'
select * from pedidoventa where pv_fecha > @fecha or pv_fecha < '20041230'
select * from pedidocompra where pc_fecha > @fecha or pc_fecha < '20041230'
select * from cobranza where cobz_fecha > @fecha or cobz_fecha < '20041230'
select * from ordenpago where opg_fecha > @fecha or opg_fecha < '20041230'
select * from movimientofondo where mf_fecha > @fecha or mf_fecha < '20041230'
select * from depositobanco where dbco_fecha > @fecha or dbco_fecha < '20041230'
select * from ordencompra where oc_fecha > @fecha or oc_fecha < '20041230'
select * from packinglist where pklst_fecha > @fecha or pklst_fecha < '20041230'
select * from asiento where as_fecha > @fecha or as_fecha < '20041230'
